import { Product, Review, User } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'electronics',
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
    images: [
      'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
    ],
    description: 'Latest iPhone with Pro camera system and titanium design',
    specifications: {
      'Display': '6.7-inch Super Retina XDR',
      'Chip': 'A17 Pro',
      'Storage': '128GB',
      'Camera': '48MP Main + 12MP Ultra Wide + 12MP Telephoto',
      'Battery': 'Up to 29 hours video playback',
    },
    averageRating: 4.7,
    totalReviews: 2847,
    prices: [
      {
        retailer: 'Apple',
        retailerLogo: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
        price: 1199,
        url: 'https://apple.com',
        availability: 'in-stock',
        shippingCost: 0,
        deliveryTime: '1-2 days',
        isOfficial: true,
        rating: 4.8,
        lastUpdated: new Date(),
      },
      {
        retailer: 'Amazon',
        retailerLogo: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
        price: 1149,
        originalPrice: 1199,
        url: 'https://amazon.com',
        availability: 'in-stock',
        shippingCost: 0,
        deliveryTime: '2-3 days',
        isOfficial: false,
        rating: 4.6,
        lastUpdated: new Date(),
      },
    ],
    isOnSale: true,
    originalPrice: 1199,
    currentPrice: 1149,
    lowestPrice: 1099,
    highestPrice: 1299,
    priceHistory: [
      { date: new Date('2024-01-01'), price: 1199, retailer: 'Apple' },
      { date: new Date('2024-01-15'), price: 1179, retailer: 'Amazon' },
      { date: new Date('2024-02-01'), price: 1149, retailer: 'Amazon' },
    ],
    availability: 'in-stock',
    shippingInfo: {
      freeShipping: true,
      estimatedDelivery: '1-2 days',
      shippingCost: 0,
    },
    deals: [
      {
        id: '1',
        type: 'discount',
        title: '4% Off',
        description: 'Save $50 on iPhone 15 Pro Max',
        discount: 50,
        expiryDate: new Date('2024-12-31'),
        retailer: 'Amazon',
      },
    ],
    similarProducts: ['2', '3'],
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'electronics',
    image: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
    images: [
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
      'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
    ],
    description: 'Premium Android phone with S Pen and advanced camera system',
    specifications: {
      'Display': '6.8-inch Dynamic AMOLED 2X',
      'Processor': 'Snapdragon 8 Gen 3',
      'Storage': '256GB',
      'Camera': '200MP Main + 50MP Periscope + 10MP Telephoto + 12MP Ultra Wide',
      'Battery': '5000mAh with 45W fast charging',
    },
    averageRating: 4.6,
    totalReviews: 1923,
    prices: [
      {
        retailer: 'Samsung',
        retailerLogo: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
        price: 1299,
        url: 'https://samsung.com',
        availability: 'in-stock',
        shippingCost: 0,
        deliveryTime: '2-3 days',
        isOfficial: true,
        rating: 4.7,
        lastUpdated: new Date(),
      },
      {
        retailer: 'Best Buy',
        retailerLogo: 'https://images.pexels.com/photos/7464284/pexels-photo-7464284.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
        price: 1249,
        originalPrice: 1299,
        url: 'https://bestbuy.com',
        availability: 'in-stock',
        shippingCost: 0,
        deliveryTime: '1-2 days',
        isOfficial: false,
        rating: 4.5,
        lastUpdated: new Date(),
      },
    ],
    isOnSale: true,
    originalPrice: 1299,
    currentPrice: 1249,
    lowestPrice: 1199,
    highestPrice: 1399,
    priceHistory: [
      { date: new Date('2024-01-01'), price: 1299, retailer: 'Samsung' },
      { date: new Date('2024-01-15'), price: 1279, retailer: 'Best Buy' },
      { date: new Date('2024-02-01'), price: 1249, retailer: 'Best Buy' },
    ],
    availability: 'in-stock',
    shippingInfo: {
      freeShipping: true,
      estimatedDelivery: '1-2 days',
      shippingCost: 0,
    },
    deals: [
      {
        id: '2',
        type: 'discount',
        title: '4% Off',
        description: 'Save $50 on Galaxy S24 Ultra',
        discount: 50,
        expiryDate: new Date('2024-12-31'),
        retailer: 'Best Buy',
      },
    ],
    similarProducts: ['1', '3'],
  },
  {
    id: '3',
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'electronics',
    image: 'https://images.pexels.com/photos/1440722/pexels-photo-1440722.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
    images: [
      'https://images.pexels.com/photos/1440722/pexels-photo-1440722.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
      'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=400&h=400',
    ],
    description: 'AI-powered Android phone with exceptional camera capabilities',
    specifications: {
      'Display': '6.7-inch LTPO OLED',
      'Processor': 'Google Tensor G3',
      'Storage': '128GB',
      'Camera': '50MP Main + 48MP Ultra Wide + 48MP Telephoto',
      'Battery': '5050mAh with 30W fast charging',
    },
    averageRating: 4.5,
    totalReviews: 1456,
    prices: [
      {
        retailer: 'Google',
        retailerLogo: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
        price: 999,
        url: 'https://store.google.com',
        availability: 'in-stock',
        shippingCost: 0,
        deliveryTime: '2-3 days',
        isOfficial: true,
        rating: 4.6,
        lastUpdated: new Date(),
      },
      {
        retailer: 'Amazon',
        retailerLogo: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
        price: 949,
        originalPrice: 999,
        url: 'https://amazon.com',
        availability: 'in-stock',
        shippingCost: 0,
        deliveryTime: '1-2 days',
        isOfficial: false,
        rating: 4.4,
        lastUpdated: new Date(),
      },
    ],
    isOnSale: true,
    originalPrice: 999,
    currentPrice: 949,
    lowestPrice: 899,
    highestPrice: 1099,
    priceHistory: [
      { date: new Date('2024-01-01'), price: 999, retailer: 'Google' },
      { date: new Date('2024-01-15'), price: 979, retailer: 'Amazon' },
      { date: new Date('2024-02-01'), price: 949, retailer: 'Amazon' },
    ],
    availability: 'in-stock',
    shippingInfo: {
      freeShipping: true,
      estimatedDelivery: '1-2 days',
      shippingCost: 0,
    },
    deals: [
      {
        id: '3',
        type: 'discount',
        title: '5% Off',
        description: 'Save $50 on Pixel 8 Pro',
        discount: 50,
        expiryDate: new Date('2024-12-31'),
        retailer: 'Amazon',
      },
    ],
    similarProducts: ['1', '2'],
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    productId: '1',
    userId: '1',
    userName: 'John Smith',
    rating: 5,
    title: 'Amazing camera quality!',
    comment: 'The camera on this phone is absolutely incredible. The low-light performance is outstanding.',
    pros: ['Excellent camera', 'Great build quality', 'Fast performance'],
    cons: ['Expensive', 'Battery could be better'],
    verified: true,
    helpful: 45,
    timestamp: new Date('2024-02-01'),
  },
  {
    id: '2',
    productId: '1',
    userId: '2',
    userName: 'Sarah Johnson',
    rating: 4,
    title: 'Great phone but pricey',
    comment: 'Love the phone overall, but the price is quite high for what you get.',
    pros: ['Fast processor', 'Good display', 'iOS ecosystem'],
    cons: ['Very expensive', 'No USB-C'],
    verified: true,
    helpful: 32,
    timestamp: new Date('2024-01-28'),
  },
];

export const MOCK_USER: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100&h=100',
  preferences: {
    preferredRetailers: ['amazon', 'bestbuy'],
    maxShippingCost: 10,
    priceAlertThreshold: 5,
    categories: ['electronics', 'home'],
    currency: 'USD',
    notifications: {
      priceDrops: true,
      deals: true,
      backInStock: true,
    },
  },
  favorites: ['1', '2'],
  priceAlerts: [
    {
      id: '1',
      productId: '1',
      targetPrice: 1100,
      isActive: true,
      createdAt: new Date('2024-02-01'),
    },
  ],
  searchHistory: [
    {
      id: '1',
      query: 'iPhone 15',
      type: 'text',
      timestamp: new Date('2024-02-01'),
      results: 25,
    },
  ],
};